[MAIN]
;Version
;{
;    auto,
;    GTA_3_1_0,
;    GTA_3_1_1,
;    GTA_3_Steam
;}
Version=auto

; dff model name, if the plugin fails to find it, it will use "trafficcone" model to prevent the game from crashing.
StingerModelName=plc_stinger

; How often cops with stingers will appear. The higher the value - the lower the probability.
CopWithStingerChance=32

; The maximum number of stingers on screen.
MaxStingers=2

; Stinger deploy animation speed(in milliseconds).
DeployTimeMs=2500

; The minimum distance from which cops are allowed to throw a stinger.
MinDeployDistance=30.0

; Stinger throw animation ID.
Anim=54